



const resources = {
  th: {
    translation: {
      home: "หน้าหลัก",
      about: "เกี่ยวกับเรา",
      service: "บริการของเรา",
      blog: "บทความ",
      contact: "ติดต่อเรา",
      login: "เข้าสู่ระบบ",
      register: "สมัครสมาชิก",
      read_more: "อ่านเพิ่มเติม",
      quick_links: "ลิงก์ด่วน",
      business_solutions: "โซลูชันธุรกิจ",
      resources: "แหล่งความรู้",
      subscribe_newsletter: "สมัครรับข่าวสาร",
      subscribe_desc: "ติดตามเทรนด์ธุรกิจ เทคโนโลยี และนวัตกรรมดิจิทัลก่อนใคร",
      enter_email: "กรอกอีเมลของคุณ",
      subscribe: "ติดตาม",
      all_rights_reserved: "สงวนลิขสิทธิ์",
      leading_business_forward: "แพลตฟอร์มธุรกิจ เพื่อต่อยอดการขายและเพิ่มประสิทธิภาพองค์กร",
      helping_business: "ช่วยให้ธุรกิจทุกขนาดเติบโตอย่างก้าวกระโดด ด้วยเทคโนโลยี โซลูชันดิจิทัล และนวัตกรรมทางธุรกิจ",
      
      register_desc: "สร้างบัญชีเพื่อเริ่มต้นใช้งาน BIZ Toptier",
      email: "อีเมล",
      phone_otp: "เบอร์โทรศัพท์ (OTP)",
      password: "รหัสผ่าน",
      phone_number: "เบอร์โทรศัพท์",
      request_otp: "ขอ OTP",
      otp_code: "รหัส OTP",
      or_register_with: "หรือสมัครด้วย",
      register_with_google: "สมัครด้วย Google",
      register_with_facebook: "สมัครด้วย Facebook",
      register_with_line: "สมัครด้วย LINE",
      already_have_account: "มีบัญชีผู้ใช้งานแล้ว?",
      login_here: "เข้าสู่ระบบ",
      web_dev: "พัฒนาเว็บไซต์ (Web Dev)",
      soft_dev: "พัฒนาซอฟต์แวร์ (Software Dev)",
      ai_sol: "โซลูชัน AI (AI Solutions)",
      bus_plat: "แพลตฟอร์มธุรกิจ (Business Platform)",
      dig_mar: "การตลาดดิจิทัล (Digital Marketing)",
      faq: "คำถามที่พบบ่อย (FAQ)",
      privacy: "นโยบายความเป็นส่วนตัว (Privacy)",
      terms: "ข้อกำหนดและเงื่อนไข (Terms)",
      cookies: "นโยบายคุกกี้ (Cookies)",
      our_services_items: {
        item1_title: "1. Business Analysis",
        item1_sub: "บริการวิเคราะห์และประเมินศักยภาพธุรกิจ",
        item1_1: "วิเคราะห์ปัญหาและความต้องการขององค์กร",
        item1_2: "ประเมินความพร้อมของธุรกิจ",
        item1_3: "ค้นหา Root Cause",
        item1_4: "จัดทำแนวทางการพัฒนา (Improvement Plan)",
        item2_title: "2. Business Matching",
        item2_sub: "บริการเชื่อมต่อธุรกิจแบบรักษาความลับ",
        item2_1: "รับ Requirement จากองค์กร",
        item2_2: "วิเคราะห์ความต้องการ",
        item2_3: "คัดกรองพันธมิตรที่เหมาะสม",
        item2_4: "ไม่เปิดเผยข้อมูลของทั้งสองฝ่าย",
        item2_5: "ประสานงานจนเกิดความร่วมมือ",
        item3_title: "3. Solution Advisory",
        item3_sub: "บริการให้คำปรึกษาและออกแบบ Solution",
        item3_desc: "เมื่อวิเคราะห์ธุรกิจแล้ว BizTopTier จะช่วยกำหนดว่าองค์กรควรใช้บริการหรือโซลูชันแบบใด เช่น:",
        item3_italic: "โดยไม่ยึดติดกับผู้ให้บริการรายใดรายหนึ่ง",
        item4_title: "4. Partner Solution Management",
        item4_sub: "บริการคัดเลือกและบริหารผู้ให้บริการ",
        item4_1: "คัดเลือกผู้ให้บริการจากเครือข่าย",
        item4_2: "เปรียบเทียบความเหมาะสม",
        item4_3: "ประเมินคุณภาพ",
        item4_4: "ประสานงาน",
        item4_5: "ติดตามผลการดำเนินงาน",
        item5_title: "5. Business Growth Support",
        item5_sub: "บริการติดตามผลและสนับสนุนการเติบโต",
        item5_1: "ติดตามผลลัพธ์หลังส่งมอบ Solution",
        item5_2: "ประเมินผลการดำเนินงาน",
        item5_3: "ให้คำแนะนำเพิ่มเติม",
        item5_4: "เชื่อมต่อ Solution ใหม่เมื่อธุรกิจมีความต้องการเพิ่มเติม"
      },
      hero: {
        subtitle: "Future Business Data Hub",
        title_1: "เชื่อมต่อทุกโอกาส",
        title_2: "ขยายเครือข่ายธุรกิจ",
        desc: "Biz Toptier คือศูนย์กลางข้อมูลสำหรับธุรกิจทุกขนาด (SME ถึง Enterprise) สร้างเครือข่ายที่แข็งแกร่ง เพื่อการแลกเปลี่ยนบริการและสินค้าแบบครบวงจร",
        start_free: "เริ่มต้นใช้งานฟรี",
        search_business: "ค้นหาธุรกิจ",
        businesses_in_system: "ธุรกิจในระบบ",
        updated_today: "อัปเดตวันนี้"
      },
      partners: {
        trusted: "Trusted by our Partners",
        title: "พาร์ทเนอร์ของเรา"
      },
      features: {
        our_services: "Why Choose Us",
        why: "ทำไมต้อง Biz Toptier?",
        desc: "เราออกแบบแพลตฟอร์มมาเพื่อตอบสนองความต้องการของธุรกิจยุคดิจิทัล ให้การค้นหา นำเสนอ และเชื่อมต่อ เป็นเรื่องง่ายและมีประสิทธิภาพสูงสุด",
        list: [
          { name: "เครือข่ายไร้รอยต่อ", desc: "เชื่อมโยงธุรกิจข้ามอุตสาหกรรม ค้นหาคู่ค้าและพันธมิตรที่เหมาะสมกับเป้าหมายของคุณได้อย่างรวดเร็ว" },
          { name: "ข้อมูลที่เชื่อถือได้", desc: "ระบบยืนยันตัวตนและโปรไฟล์ธุรกิจที่ชัดเจน สร้างความมั่นใจในการเจรจาและทำธุรกรรม" },
          { name: "เจรจาธุรกิจโดยตรง", desc: "ลดตัวกลาง เพิ่มผลกำไร ด้วยช่องทางการติดต่อโดยตรงระหว่างผู้ประกอบการกับผู้ประกอบการ (B2B)" },
          { name: "วิเคราะห์การเติบโต", desc: "เข้าถึงข้อมูลเชิงลึก ภาพรวมตลาด และเทรนด์ธุรกิจเพื่อประกอบการตัดสินใจที่แม่นยำ" }
        ]
      },
      services_section: {
        subtitle: "Our Service",
        title: "บริการของเรา",
        features_title: "ความเชี่ยวชาญของเรา",
        items: [
          {
            title: "Business Health Check",
            desc: "วิเคราะห์ธุรกิจอย่างเป็นระบบ เพื่อค้นหาโอกาสในการเติบโต",
            highlight: "เปลี่ยนข้อมูลธุรกิจ ให้กลายเป็นแผนการเติบโต",
            features: [
              "วิเคราะห์ธุรกิจแบบ 360°",
              "ค้นหาปัญหาและจุดอ่อนที่มองไม่เห็น",
              "แนะนำแนวทางเพิ่มยอดขายและลดต้นทุน",
              "วิเคราะห์คู่แข่งและโอกาสทางการตลาด",
              "จัดทำแผนพัฒนาธุรกิจที่นำไปใช้ได้จริง",
              "เหมาะสำหรับธุรกิจที่ต้องการเติบโตอย่างยั่งยืน"
            ]
          },
          {
            title: "Website Development",
            desc: "ออกแบบและพัฒนาเว็บไซต์ที่สร้างความน่าเชื่อถือและเพิ่มโอกาสทางธุรกิจ",
            highlight: "เว็บไซต์ที่ไม่ได้มีไว้แค่สวย แต่ช่วยสร้างยอดขาย",
            features: [
              "ออกแบบเฉพาะตามแบรนด์",
              "รองรับทุกอุปกรณ์ (Responsive)",
              "SEO Friendly",
              "ระบบจัดการข้อมูล (CMS)",
              "เชื่อมต่อ Google Analytics, Facebook Pixel และระบบ Marketing",
              "รองรับการขยายระบบในอนาคต",
              "ความปลอดภัยสูง พร้อมบริการดูแลหลังส่งมอบ"
            ]
          },
          {
            title: "Application Development",
            desc: "พัฒนา Web Application และ Mobile Application ตามความต้องการของธุรกิจ",
            highlight: "เปลี่ยนขั้นตอนการทำงานที่ซับซ้อน ให้เป็นระบบอัตโนมัติ",
            features: [
              "วิเคราะห์และออกแบบระบบก่อนพัฒนา",
              "พัฒนาเฉพาะสำหรับแต่ละองค์กร",
              "รองรับ Web, iOS และ Android",
              "Dashboard และระบบรายงาน",
              "เชื่อมต่อ API และระบบภายนอก",
              "รองรับการเติบโตของธุรกิจ (Scalable)",
              "ดูแลและพัฒนาต่อได้ในระยะยาว"
            ]
          },
          {
            title: "Google Ads Management",
            desc: "เพิ่มโอกาสในการเข้าถึงลูกค้าที่กำลังค้นหาสินค้าหรือบริการของคุณ",
            highlight: "ใช้งบอย่างคุ้มค่า เข้าถึงลูกค้าที่พร้อมซื้อ",
            features: [
              "วางกลยุทธ์ก่อนเริ่มโฆษณา",
              "Keyword Research",
              "เขียนโฆษณาที่เพิ่ม Conversion",
              "ปรับแต่งแคมเปญอย่างต่อเนื่อง",
              "วิเคราะห์ข้อมูลและจัดทำรายงาน",
              "เพิ่มประสิทธิภาพงบโฆษณา (ROAS)",
              "ติดตั้ง Tracking และ Conversion"
            ]
          },
          {
            title: "IT & Business Solutions Consulting",
            desc: "ที่ปรึกษาด้านเทคโนโลยีและกลยุทธ์ธุรกิจ เพื่อยกระดับองค์กร",
            highlight: "เทคโนโลยีที่เหมาะสม คือการลงทุนที่สร้างผลตอบแทนให้ธุรกิจ",
            features: [
              "วิเคราะห์ปัญหาและกระบวนการทำงาน",
              "วางแผน Digital Transformation",
              "ให้คำปรึกษาการเลือกใช้เทคโนโลยี",
              "วางโครงสร้างระบบ IT",
              "ปรับปรุง Workflow และเพิ่มประสิทธิภาพ",
              "วาง Roadmap การพัฒนาระยะยาว",
              "ให้คำแนะนำด้าน Business Process และ Automation"
            ]
          }
        ]
      },
      latest_blogs: {
        title: "บทความล่าสุด",
        subtitle: "อัปเดตความรู้และเทรนด์ธุรกิจเพื่อก้าวสู่มาตรฐาน Top Tier",
        view_all: "ดูบทความทั้งหมด"
      },
      admin: {
        settings: "ตั้งค่า",
        analytics: "สถิติการใช้งาน",
        financial: "รายได้",
        packages: "แพ็กเกจ",
        media: "ไฟล์ที่อัปโหลด",
        membership: "สมาชิก",
        dashboard: "แผงควบคุม",
        pages: "จัดการหน้าเพจ",
        blogs: "บทความทั้งหมด",
        add_blog: "เขียนบทความใหม่",
        categories: "หมวดหมู่บทความ",
        logout: "ออกจากระบบ",
        title_label: "หัวข้อ",
        slug_label: "ลิงก์ (Slug)",
        seo_desc: "รายละเอียด SEO",
        tags_label: "แท็ก",
        publish_time: "เวลาเผยแพร่",
        publish_setting: "การเผยแพร่",
        recommend_size: "ขนาดที่แนะนำ",
        related_posts: "บทความที่เกี่ยวข้อง",
        relationships: "ความสัมพันธ์",
        select_category: "เลือกหมวดหมู่",
        seo_sharing: "SEO & การแชร์",
        social_share_desc: "รายละเอียดการแชร์",
        social_share_preview: "ตัวอย่างการแชร์",
        upload_cover: "อัปโหลดรูปปก",
        video_desc: "รายละเอียดวิดีโอ",
        video_label: "วิดีโอ",
        video_url: "ลิงก์วิดีโอ",
        actions_label: "จัดการ",
        all_categories: "ทุกหมวดหมู่",
        author_label: "ผู้เขียน",
        blog_desc: "รายละเอียดบทความ",
        blog_management: "จัดการบทความ",
        category_label: "หมวดหมู่",
        date_label: "วันที่",
        loading: "กำลังโหลด...",
        no_data: "ไม่มีข้อมูล",
        status_label: "สถานะ",
        views_label: "ยอดเข้าชม",
        category_desc: "รายละเอียดหมวดหมู่",
        category_management: "จัดการหมวดหมู่",
        name: "ชื่อ",
        active_packages: "แพ็กเกจที่ใช้งาน",
        add_member: "เพิ่มสมาชิก",
        create_article: "สร้างบทความ",
        create_invoice: "สร้างใบแจ้งหนี้",
        enterprise_dashboard: "แดชบอร์ดองค์กร",
        export_report: "ส่งออกรายงาน",
        last_12_months: "12 เดือนล่าสุด",
        last_year: "ปีที่แล้ว",
        manage_packages: "จัดการแพ็กเกจ",
        quick_actions: "เมนูด่วน",
        revenue_mtd: "รายได้เดือนนี้",
        revenue_overview: "ภาพรวมรายได้",
        this_year: "ปีนี้",
        total_members: "สมาชิกทั้งหมด",
        visitors_7_days: "ผู้เข้าชม (7 วัน)",
        vs_last_month: "เทียบกับเดือนที่แล้ว",
        welcome_back: "ยินดีต้อนรับกลับ",
        amount: "จำนวนเงิน",
        customer: "ลูกค้า",
        date: "วันที่",
        financial_desc: "รายละเอียดการเงิน",
        financial_overview: "ภาพรวมการเงิน",
        invoice_id: "รหัสใบแจ้งหนี้",
        invoices_awaiting: "รอการชำระ",
        mrr: "รายได้ประจำรายเดือน (MRR)",
        package: "แพ็กเกจ",
        package_sales_dist: "สัดส่วนยอดขายแพ็กเกจ",
        pending_payments: "รอชำระเงิน",
        recent_orders: "รายการล่าสุด",
        refunds: "คืนเงิน",
        revenue_trend: "แนวโน้มรายได้",
        status: "สถานะ",
        total_revenue_ytd: "รายได้รวม (YTD)",
        view_all: "ดูทั้งหมด",
        vs_last_year: "เทียบกับปีที่แล้ว",
        actions: "จัดการ",
        click_or_drag: "คลิกหรือลากไฟล์มาที่นี่",
        folders: "โฟลเดอร์",
        media_desc: "รายละเอียดไฟล์",
        media_library: "คลังสื่อ",
        search: "ค้นหา",
        size: "ขนาด",
        supports_files: "รองรับไฟล์",
        joined: "เข้าร่วมเมื่อ",
        member_name: "ชื่อสมาชิก",
        membership_desc: "รายละเอียดสมาชิก",
        membership_management: "จัดการสมาชิก",
        active_users: "ผู้ใช้งาน",
        duration: "ระยะเวลา",
        featured: "แนะนำ",
        package_desc: "รายละเอียดแพ็กเกจ",
        package_details: "ข้อมูลแพ็กเกจ",
        package_management: "จัดการแพ็กเกจ",
        pricing: "ราคา",
        create_page: "สร้างหน้าเพจ",
        desc_label: "รายละเอียด",
        edit_page: "แก้ไขหน้าเพจ",
        favicon_url: "ไอคอนเว็บไซต์ (Favicon)",
        footer_script: "สคริปต์ส่วนท้าย",
        general_info: "ข้อมูลทั่วไป",
        html_editor: "ตัวแก้ไข HTML",
        page_settings: "ตั้งค่าหน้าเพจ",
        scripts_label: "สคริปต์",
        seo_tags: "แท็ก SEO",
        last_updated_label: "อัปเดตล่าสุด",
        page_desc: "รายละเอียดหน้าเพจ",
        page_management: "จัดการหน้าเพจ",
        activity_logs: "บันทึกกิจกรรม",
        api_integration: "เชื่อมต่อ API",
        backup_restore: "สำรอง/กู้คืนข้อมูล",
        company_name: "ชื่อบริษัท",
        contact_email: "อีเมลติดต่อ",
        currency: "สกุลเงิน",
        default_language: "ภาษาเริ่มต้น",
        email_smtp: "อีเมล SMTP",
        general: "ทั่วไป",
        general_settings: "ตั้งค่าทั่วไป",
        localization: "ภาษาและภูมิภาค",
        phone_number: "เบอร์โทรศัพท์",
        security: "ความปลอดภัย",
        security_policies: "นโยบายความปลอดภัย",
        settings_desc: "รายละเอียดการตั้งค่า",
        strong_password: "รหัสผ่านที่รัดกุม",
        strong_password_desc: "บังคับใช้รหัสผ่านที่รัดกุม",
        system_settings: "ตั้งค่าระบบ",
        timezone: "เขตเวลา",
        two_factor: "ยืนยันตัวตน 2 ขั้นตอน (2FA)",
        two_factor_desc: "เปิดใช้งาน 2FA",
        website_name: "ชื่อเว็บไซต์",
        add_page: "เพิ่มหน้าเพจ"
      }
    }
  },
  en: {
    translation: {
      home: "Home",
      about: "About",
      service: "Service",
      blog: "Blog",
      contact: "Contact",
      login: "Login",
      register: "Register",
      read_more: "Read More",
      quick_links: "Quick Links",
      business_solutions: "Business Solutions",
      resources: "Resources",
      subscribe_newsletter: "Subscribe Newsletter",
      subscribe_desc: "Stay updated with business trends, technology, and digital innovation.",
      enter_email: "Enter your email",
      subscribe: "Subscribe",
      all_rights_reserved: "All Rights Reserved",
      leading_business_forward: "Business Platform to boost sales and enhance organizational efficiency",
      helping_business: "Helping businesses of every size grow through technology, digital solutions, and business innovation.",
      
      register_desc: "Create an account to get started with BIZ Toptier",
      email: "Email",
      phone_otp: "Phone Number (OTP)",
      password: "Password",
      phone_number: "Phone Number",
      request_otp: "Request OTP",
      otp_code: "OTP Code",
      or_register_with: "Or register with",
      register_with_google: "Register with Google",
      register_with_facebook: "Register with Facebook",
      register_with_line: "Register with LINE",
      already_have_account: "Already have an account?",
      login_here: "Login here",
      web_dev: "Web Development",
      soft_dev: "Software Development",
      ai_sol: "AI Solutions",
      bus_plat: "Business Platform",
      dig_mar: "Digital Marketing",
      faq: "FAQ",
      privacy: "Privacy Policy",
      terms: "Terms & Conditions",
      cookies: "Cookie Policy",
      our_services_items: {
        item1_title: "1. Business Analysis",
        item1_sub: "Business analysis and potential assessment service",
        item1_1: "Analyze organizational problems and needs",
        item1_2: "Assess business readiness",
        item1_3: "Find Root Cause",
        item1_4: "Create an Improvement Plan",
        item2_title: "2. Business Matching",
        item2_sub: "Confidential business matching service",
        item2_1: "Receive Requirements from organizations",
        item2_2: "Analyze needs",
        item2_3: "Screen suitable partners",
        item2_4: "Keep information of both parties confidential",
        item2_5: "Coordinate until cooperation occurs",
        item3_title: "3. Solution Advisory",
        item3_sub: "Consulting and Solution design service",
        item3_desc: "After business analysis, BizTopTier will help determine what services or solutions the organization should use, such as:",
        item3_italic: "Without being tied to any specific provider",
        item4_title: "4. Partner Solution Management",
        item4_sub: "Provider selection and management service",
        item4_1: "Select providers from the network",
        item4_2: "Compare suitability",
        item4_3: "Assess quality",
        item4_4: "Coordinate",
        item4_5: "Track performance",
        item5_title: "5. Business Growth Support",
        item5_sub: "Follow-up and growth support service",
        item5_1: "Track results after Solution delivery",
        item5_2: "Assess performance",
        item5_3: "Provide additional advice",
        item5_4: "Connect new Solutions when business has additional needs"
      },
      hero: {
        subtitle: "Future Business Data Hub",
        title_1: "Connect Every Opportunity",
        title_2: "Expand Business Network",
        desc: "Biz Toptier is an information hub for businesses of all sizes (SME to Enterprise). Build a strong network for comprehensive service and product exchange.",
        start_free: "Start for free",
        search_business: "Search Business",
        businesses_in_system: "Businesses in system",
        updated_today: "Updated today"
      },
      partners: {
        trusted: "Trusted by our Partners",
        title: "Our Partners"
      },
      features: {
        our_services: "Why Choose Us",
        why: "Why Biz Toptier?",
        desc: "We designed a platform to meet the needs of digital businesses, making searching, presenting, and connecting easy and highly efficient.",
        list: [
          { name: "Seamless Network", desc: "Connect businesses across industries, quickly find partners that match your goals." },
          { name: "Reliable Data", desc: "Clear identity verification and business profiles, building confidence in negotiations and transactions." },
          { name: "Direct Business Negotiation", desc: "Reduce middlemen, increase profit with direct B2B communication channels." },
          { name: "Growth Analysis", desc: "Access insights, market overview, and business trends for accurate decision making." }
        ]
      },
      services_section: {
        subtitle: "Our Service",
        title: "Our Services",
        features_title: "Our Expertise",
        items: [
          {
            title: "Business Health Check",
            desc: "Systematically analyze your business to find growth opportunities",
            highlight: "Turn business data into a growth plan",
            features: [
              "360° business analysis",
              "Find hidden problems and weaknesses",
              "Recommend ways to increase sales and reduce costs",
              "Analyze competitors and market opportunities",
              "Create practical business development plans",
              "Suitable for businesses looking for sustainable growth"
            ]
          },
          {
            title: "Website Development",
            desc: "Design and develop websites that build trust and increase business opportunities",
            highlight: "A website that is not just beautiful, but helps generate sales",
            features: [
              "Custom design tailored to your brand",
              "Supports all devices (Responsive)",
              "SEO Friendly",
              "Content Management System (CMS)",
              "Connect Google Analytics, Facebook Pixel, and marketing systems",
              "Supports future system expansion",
              "High security with post-delivery maintenance services"
            ]
          },
          {
            title: "Application Development",
            desc: "Develop Web and Mobile Applications according to business needs",
            highlight: "Turn complex workflows into automated systems",
            features: [
              "Analyze and design the system before development",
              "Custom developed for each organization",
              "Supports Web, iOS, and Android",
              "Dashboard and reporting system",
              "Connect APIs and external systems",
              "Supports business growth (Scalable)",
              "Long-term maintenance and further development"
            ]
          },
          {
            title: "Google Ads Management",
            desc: "Increase opportunities to reach customers searching for your products or services",
            highlight: "Spend budget wisely, reach ready-to-buy customers",
            features: [
              "Strategize before starting ads",
              "Keyword Research",
              "Write ads that increase conversion",
              "Continuously optimize campaigns",
              "Analyze data and create reports",
              "Optimize ad budget (ROAS)",
              "Install tracking and conversion"
            ]
          },
          {
            title: "IT & Business Solutions Consulting",
            desc: "Technology and business strategy consultant to elevate your organization",
            highlight: "The right technology is an investment that generates returns for your business",
            features: [
              "Analyze problems and workflows",
              "Plan Digital Transformation",
              "Consult on technology selection",
              "Layout IT system structure",
              "Improve workflow and increase efficiency",
              "Plan long-term development roadmap",
              "Advise on business processes and automation"
            ]
          }
        ]
      },
      latest_blogs: {
        title: "Latest Blogs",
        subtitle: "Update knowledge and business trends to reach Top Tier standards",
        view_all: "View all blogs"
      },
      admin: {
        settings: "Settings",
        analytics: "Analytics",
        financial: "Financial",
        packages: "Package",
        media: "Upload",
        membership: "Member",
        dashboard: "Dashboard",
        pages: "Pages",
        blogs: "All Blogs",
        add_blog: "Add Blog",
        categories: "Categories",
        logout: "Logout",
        title_label: "Title",
        slug_label: "Slug",
        seo_desc: "SEO Description",
        tags_label: "Tags",
        publish_time: "Publish Time",
        publish_setting: "Publishing",
        recommend_size: "Recommended Size",
        related_posts: "Related Posts",
        relationships: "Relationships",
        select_category: "Select Category",
        seo_sharing: "SEO & Sharing",
        social_share_desc: "Social Share Description",
        social_share_preview: "Social Share Preview",
        upload_cover: "Upload Cover",
        video_desc: "Video Description",
        video_label: "Video",
        video_url: "Video URL",
        actions_label: "Actions",
        all_categories: "All Categories",
        author_label: "Author",
        blog_desc: "Blog Description",
        blog_management: "Blog Management",
        category_label: "Category",
        date_label: "Date",
        loading: "Loading...",
        no_data: "No data",
        status_label: "Status",
        views_label: "Views",
        category_desc: "Category Description",
        category_management: "Category Management",
        name: "Name",
        active_packages: "Active Packages",
        add_member: "Add Member",
        create_article: "Create Article",
        create_invoice: "Create Invoice",
        enterprise_dashboard: "Enterprise Dashboard",
        export_report: "Export Report",
        last_12_months: "Last 12 Months",
        last_year: "Last Year",
        manage_packages: "Manage Packages",
        quick_actions: "Quick Actions",
        revenue_mtd: "Revenue (MTD)",
        revenue_overview: "Revenue Overview",
        this_year: "This Year",
        total_members: "Total Members",
        visitors_7_days: "Visitors (7 Days)",
        vs_last_month: "vs Last Month",
        welcome_back: "Welcome back",
        amount: "Amount",
        customer: "Customer",
        date: "Date",
        financial_desc: "Financial Description",
        financial_overview: "Financial Overview",
        invoice_id: "Invoice ID",
        invoices_awaiting: "Awaiting Payment",
        mrr: "Monthly Recurring Revenue (MRR)",
        package: "Package",
        package_sales_dist: "Package Sales Distribution",
        pending_payments: "Pending Payments",
        recent_orders: "Recent Orders",
        refunds: "Refunds",
        revenue_trend: "Revenue Trend",
        status: "Status",
        total_revenue_ytd: "Total Revenue (YTD)",
        view_all: "View All",
        vs_last_year: "vs Last Year",
        actions: "Actions",
        click_or_drag: "Click or drag file here",
        folders: "Folders",
        media_desc: "Media Description",
        media_library: "Media Library",
        search: "Search",
        size: "Size",
        supports_files: "Supports files",
        joined: "Joined",
        member_name: "Member Name",
        membership_desc: "Membership Description",
        membership_management: "Membership Management",
        active_users: "Active Users",
        duration: "Duration",
        featured: "Featured",
        package_desc: "Package Description",
        package_details: "Package Details",
        package_management: "Package Management",
        pricing: "Pricing",
        create_page: "Create Page",
        desc_label: "Description",
        edit_page: "Edit Page",
        favicon_url: "Favicon URL",
        footer_script: "Footer Script",
        general_info: "General Info",
        html_editor: "HTML Editor",
        page_settings: "Page Settings",
        scripts_label: "Scripts",
        seo_tags: "SEO Tags",
        last_updated_label: "Last Updated",
        page_desc: "Page Description",
        page_management: "Page Management",
        activity_logs: "Activity Logs",
        api_integration: "API Integration",
        backup_restore: "Backup / Restore",
        company_name: "Company Name",
        contact_email: "Contact Email",
        currency: "Currency",
        default_language: "Default Language",
        email_smtp: "Email SMTP",
        general: "General",
        general_settings: "General Settings",
        localization: "Localization",
        phone_number: "Phone Number",
        security: "Security",
        security_policies: "Security Policies",
        settings_desc: "Settings Description",
        strong_password: "Strong Password",
        strong_password_desc: "Enforce strong passwords",
        system_settings: "System Settings",
        timezone: "Timezone",
        two_factor: "Two-Factor Auth (2FA)",
        two_factor_desc: "Enable 2FA",
        website_name: "Website Name",
        add_page: "Add Page"
      }
    }
  }
};

console.log(JSON.stringify(resources, null, 2));